Repository hmcts/rd-professional-api, pull requests merged in 2020-12, with the labels that each got.

#916 fix: adding '@Ignore' to functional tests to be converted
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AddNewUserTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/DeleteOrganisationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/UserRolesTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-916

#924 Nightly build issue fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-924

#918 Add method call to sync branches
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-918

#925 DTSPO-266 Enable self service read only access
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-925

#932 Bump : RDCC2017 Bump up Jar versions
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-932

#933 Bump : RDCC-2017 Bump up jar versions
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-933

#940 Fix: Fixing the CVE 2020-8908
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-940
