Repository hmcts/rd-professional-api, pull requests merged in 2021-08, with the labels that each got.

#1072 RDCC-3168: Addressing Sonar Issues in Master
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/PaymentAccountValidator.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/UserAttributeServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/advice/ExceptionMapperTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalControllerTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserControllerTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalControllerTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1072

#1075 RDCC-3205 - PRD API - Update delete script in Jenkins nightly job
  charts/rd-professional-api/Chart.yaml
  deletescript/sql/delete-functional-test-data.sql
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1075

#1081 RDCC-3237 - Fix CVE issue : CVE-2021-28170, CVE-2021-22119
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1081

#1083 Fixing Nightly Build (Security Scan Issue): Adding entries to audit.json
  audit.json
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1083

#1085 RDCC-3254 - Suppressed CVE-2020-23171
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1085

#1086 RDCC-3239- Fix Security scan issue
  security.sh
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1086

#1087 DCC-3116: PRD_3.0 - Add more than 1 PBA/Update PBAs during Org Activation
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalInternalControllerProviderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrganisationWithPaymentAccountTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/UpdateOrganisationTest.java
  src/integrationTest/resources/db/migration/V6_19__adding_new_pba_columns_and_update_existing_pbas.sql
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/domain/PaymentAccount.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/domain/PbaStatus.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/OrganisationService.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/PaymentAccountServiceImpl.java
  src/main/resources/db/migration/V6_19__adding_new_pba_columns_and_update_existing_pbas.sql
  src/main/resources/db/postgres/V6_20__update_existing_pbas_to_accepted.sql
  src/test/java/uk/gov/hmcts/reform/professionalapi/domain/PaymentAccountTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/helper/BaseRepository.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1087
