Repository hmcts/rd-professional-api, pull requests merged in 2021-12, with the labels that each got.

#1126 RDCC-3650: Enhance PBA DB calls
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/DeletePaymentAccountsIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/PaymentAccountValidator.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/impl/OrganisationIdentifierValidatorImpl.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/PaymentAccountValidatorTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1126

#1125 RDCC-3657: Refactoring to implement Java 11 features
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/IntegrationTestOidcSecurityConfig.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/advice/ExceptionMapper.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/advice/LogAndSuppressRequestRejectedExceptionFilter.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/UserAttributeRequest.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/ProfessionalUserReqValidator.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/impl/OrganisationIdentifierValidatorImpl.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ContactInformationResponseWithDxAddress.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationsDetailResponse.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/domain/UserAccountMap.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/repository/IdamRepository.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/PaymentAccountServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/UserAccountMapServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/util/JsonFeignResponseUtil.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/SuperControllerTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationMfaStatusControllerTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/ContactInformationCreationRequestTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/PbaAccountCreationRequestTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/PbaEditRequestTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/RetrieveUserProfilesRequestTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/UserAttributeRequestTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/UserProfileCreationRequestTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/PaymentAccountValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/impl/OrganisationIdentifierValidatorImplTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/impl/UserProfileUpdateRequestValidatorImplTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/ContactInformationResponseWithDxAddressTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/MultipleUserProfilesResponseTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/NewUserResponseTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationPbaResponseTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/UserProfileCreationResponseTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/domain/ContactInformationTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/domain/OrganisationMfaStatusTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/domain/RoleAdditionResponseTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/domain/RoleDeletionResponseTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/domain/StatusUpdateResponseTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/helper/OrganisationFixtures.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/PaymentAccountServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/PrdEnumServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/UserAccountMapServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/UserAttributeServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1125

#1127 RDCC-3730: increase mutation coverage for new PBA code
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/PaymentAccountValidator.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/PaymentAccountServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/UserAttributeServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1127

#1128 fix: RDCC-3655 Replaced valid email domain in test classes with dummy email domain
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalExternalControllerProviderUsersTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateMinimalOrganisationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateNewUserWithRolesTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindPaymentAccountsByEmailTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/SuperControllerTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/NewUserCreationRequestTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/UserCreationRequestTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/UserProfileCreationRequestTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/ProfessionalUsersEntityResponseTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/domain/UserProfileUpdatedDataTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/helper/OrganisationFixtures.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/UserAttributeServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtilTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1128

#1129 RDCC-3768: Disabled fortify scan until further notice
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1129

#1130 fix: RDCC-3773 patch log4j to the latest version
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1130

#1132 RDCC-3799: upgrading log4j to '2.16.0'
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1132

#1133 RDCC-3786: Collating Dependabot PRs
  .dependabot/config.yml
  .github/dependabot.yml
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1133

#1149 Fix: Upgrading log4j to fix CVE-2021-45105
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1149
