Repository hmcts/rd-professional-api, pull requests merged in 2021-03, with the labels that each got.

#986 fix: RDCC-2507 Upgraded spring boot version to fix CVE CVE-2021-22112
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-986

#985 Update app insights secret key name
  charts/rd-professional-api/Chart.yaml
  charts/rd-professional-api/values.preview.template.yaml
  charts/rd-professional-api/values.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-985

#983 feat: RDCC-2497: Added citizen,caseworker roles and removed user is active …
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalExternalUserFunctionalTest.java
  src/functionalTest/resources/application-functional.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveMinimalOrganisationsInfoIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalControllerTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-983

#988 fix: Remove launch darkly flags from PRD application
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/DeleteOrganisationIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveMinimalOrganisationsInfoIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/LaunchDarklyConfiguration.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/FeatureToggleServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/FeatureToggleServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-988

#999 RDCC-1985: removing unwanted suppressions
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-999

#1001 RDCC-1985: removing unwanted suppressions
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1001

#1003 fix:RDCC-2632 added hikari configuration
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1003
