Repository hmcts/rd-professional-api, pull requests merged in 2021-07, with the labels that each got.

#1066 updated the order of command in security.sh to fixed security scan
  security.sh
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1066

#1065 Add auto-update config for PR branches
  .github/workflows/autoupdate.yml
Labels: DO NOT MERGE, ns:rd, prd:rd, rel:rd-professional-api-pr-1065

#1067 fix: RDCC-3087 extended the suppression date as the fix is not yet pr…
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1067

#1068 RDCC-3033 handling 500 request responses
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindPaymentAccountsByEmailTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationEntityResponse.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/util/JsonFeignResponseUtil.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtil.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalControllerTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalControllerTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationEntityResponseTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtilTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1068

#1070 test: RDCC-2980 added provider test for MFA functionality
  build.gradle
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/pact/util/PactUtils.java
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalExternalControllerProviderTestConfiguration.java
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalInternalControllerProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalMfaStatusControllerProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/ProfessionalExternalUserControllerProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/ProviderTestConfiguration.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1070

#1071 fix: Remove bintray reference(RDCC-3150)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1071

#1069 RDCC-2820: Deprecation of Email as a Query Param in APIs
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/EditPaymentAccountsTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindPaymentAccountsByEmailTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/SuperControllerTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalControllerTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalControllerTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1069

#1074 RDCC-3167 Adding security fix for nightly
  audit.json
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1074
