Repository hmcts/rd-professional-api, pull requests merged in 2021-11, with the labels that each got.

#1112 fix: RDCC-3557 Upgraded spring boot version to fix CVE-2021-22096
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1112

#1113 Added postgresql_version
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1113

#1115 Create postgres v11 DB on all environments
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1115

#1118 CHG5006041 - Add secret to store v11 DB secrets
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1118

#1119 Update configurations to point to v1 DB
  charts/rd-professional-api/Chart.yaml
  charts/rd-professional-api/values.aat.template.yaml
  charts/rd-professional-api/values.yaml
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1119

#1120 RDCC-3644: PRD - CVE suppression extension
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1120

#1121 Publish Jenkins Report
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1121

#1123 Nightly Fix: Adding entries to audit.json
  audit.json
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1123

#1124 Delete v9.6 DB
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1124
