Repository hmcts/rd-professional-api, pull requests merged in 2021-06, with the labels that each got.

#1050 RDCC-2838 - changed all Gradle 7 deprecrated entries
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1050

#1057 upgarded spring boot version from 2.4.5 to 2.4.6
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1057

#1058 RDCC-2970- Update Jenkins nightly file to generate the serenity report
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1058
