Repository hmcts/rd-professional-api, pull requests merged in 2022-07, with the labels that each got.

#1288 cve fix
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1288

#1289 RDCC-5023: Nightly Build Fix - adding entries to `audit.json`
  audit.json
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1289

#1290 RDCC-5047 Upgrade java chart
  charts/rd-professional-api/Chart.yaml
  charts/rd-professional-api/values.preview.template.yaml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1290

#1299 RDCC-5138: Adding Suppression for `CVE-2022-31569`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1299

#1300 RDCC-5152: Adding entry to `audit.json`
  audit.json
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1300
