Repository hmcts/rd-professional-api, pull requests merged in 2022-10, with the labels that each got.

#1324 RDCC-5534: Upgrading `launchdarkly-java-server-sdk` & `snakeyaml`
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1324

#1303 RDCC-4677: PRD : Add pagination as an optional parameter to retrieve organisation details API
  build.gradle
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalInternalControllerProviderTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/impl/OrganisationStatusValidatorImpl.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationsDetailResponse.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/repository/OrganisationRepository.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/OrganisationService.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/SuperControllerTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalControllerTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/impl/OrganisationStatusValidatorImplTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationsDetailResponseTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1303

#1325 CVE Issue Fix- Jackson Version change 2.14.0-rc1
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1325

#1327 Add Entry in to audit.json to resolve security scan issues
  audit.json
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1327

#1328 RDCC-5592:rd-professional-api code smell issues fixes
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/advice/ExceptionMapper.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/DxAddressCreationRequest.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidator.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/impl/OrganisationStatusValidatorImpl.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationEntityResponse.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/advice/UnauthorizedExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1328
