Repository hmcts/rd-professional-api, pull requests merged in 2022-08, with the labels that each got.

#1304 Address CVE-2021-28170
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1304

#1302 RDCC-5082: Populating Pending PBAs List for Get PBA by Email APIs
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalExternalControllerProviderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/AddPaymentAccountsIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1302

#1306 RDCC-5216: Adding Entries to `audit.json` to fix Security Scan
  audit.json
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1306

#1309 Remove Transfer encoding
  build.gradle
  src/main/java/uk/gov/hmcts/reform/professionalapi/util/JsonFeignResponseUtil.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1309

#1310 Add backstage configuration file
  catalog-info.yaml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1310

#1313 Use latest agent
  Dockerfile
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1313

#1315 upgrade feign client
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1315
