Repository hmcts/rd-professional-api, pull requests merged in 2022-09, with the labels that each got.

#1316 CVE FIX
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1316

#1317 RDCC-5447: Suppress Snakeyaml CVEs
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1317

#1318 RDCC-5110: Updating Add PBA API to Add Entries to User Account Map
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/EditPaymentAccountsTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/OrganisationService.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1318

#1323 Nightly Fix: Updating security.sh
  security.sh
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1323
