Repository hmcts/rd-professional-api, pull requests merged in 2022-05, with the labels that each got.

#1224 RDCC-4576: Increase Size Constraint of DX Exchange
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/AddContactInformationToOrganisationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrgWithContactInformationDxAddress.java
  src/integrationTest/resources/db/migration/V10__alter_dx_exchange.sql
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidator.java
  src/main/resources/db/migration/V10__alter_dx_exchange.sql
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/domain/DxAddressTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1224

#1227 CVE Fix for LaunchDarklySDK
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1227

#1228 RDCC-4648: Increasing `CVE-2020-23171` Suppression Date
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1228

#1229 RDCC-4690: Suppressing `CVE-2016-1000027`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1229

#1231 CVE Fix for Tomcat Embed Core n websocket
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1231

#1234 CVE fix: Bumped spring dependencies version to 5.3.20
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1234
