Repository hmcts/rd-professional-api, pull requests merged in 2022-04, with the labels that each got.

#1217 RDCC-4402: CVE Fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1217

#1216 FEAT: Java 17 upgrade
  Dockerfile
  build.gradle
  docker-compose.yml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1216

#1221 RDCC-4468: Nightly Fix - Adding Entries to audit.json
  audit.json
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1221

#1223 CVE Fix for SpringCore
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1223

#1220 RDCC-4453: Addressing Sonar Issues
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidator.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/PaymentAccountValidator.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/ProfessionalUserReqValidator.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/impl/OrganisationStatusValidatorImpl.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ContactInformationResponseWithDxAddress.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/MultipleUserProfilesResponse.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationEntityResponse.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationMinimalInfoResponse.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationsDetailResponse.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/repository/OrganisationRepository.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/PaymentAccountServiceImpl.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1220

#1222 feat: RDCC-4493 Used the New Common Library and removed the unwanted code
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/EndpointSecurityTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalExternalUserFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/SerenityTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/SerenityTestWithoutReporting.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/counter/TestCountListener.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/counter/TestCounter.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/SerenityExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/SerenityJUnitLifecycleAdapterExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/SerenityManualExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/SerenityReportExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/SerenityStepExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/page/PatchedManagedWebDriverAnnotatedField.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/page/SerenityPageExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/page/TestConfiguration.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/page/TestMethodAnnotations.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/guice/JUnit5Module.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/guice/JUnitInjectors.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/ModifyUserStatusIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/SerenityTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/SerenityTestWithoutReporting.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/counter/TestCountListener.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/counter/TestCounter.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/SerenityExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/SerenityJUnitLifecycleAdapterExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/SerenityManualExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/SerenityReportExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/SerenityStepExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/page/PatchedManagedWebDriverAnnotatedField.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/page/SerenityPageExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/page/TestConfiguration.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/extension/page/TestMethodAnnotations.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/guice/JUnit5Module.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/serenity5/guice/JUnitInjectors.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/advice/LogAndSuppressRequestRejectedExceptionFilter.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1222
