Repository hmcts/rd-professional-api, pull requests merged in 2022-11, with the labels that each got.

#1322 Rdcc ex UI change
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/ProfessionalUserReqValidator.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/repository/ProfessionalUserRepository.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/ProfessionalUserService.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserControllerTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalControllerTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/ProfessionalUserReqValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/repository/ProfessionalUserRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1322

#1329 RDCC-5778: Upgrading `tomcat` to version `9.0.68`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1329

#1331 RDCC-5801: Nightly Fix - Adding entries to `audit.json`
  audit.json
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1331

#1332 Revert "RDCC-5592:rd-professional-api code smell issues fixes"
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/advice/ExceptionMapper.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/DxAddressCreationRequest.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidator.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/impl/OrganisationStatusValidatorImpl.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationEntityResponse.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/advice/UnauthorizedExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1332

#1334 Upgrade Terraform version 1.3.X :: RDCC-5894
  infrastructure/.terraform-version
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1334

#1335 Upgrade Terraform and helm :: RDCC-5894
  charts/rd-professional-api/Chart.yaml
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1335

#1337 CVE Fix for postgresql
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1337
