Repository hmcts/rd-professional-api, pull requests merged in 2023-09, with the labels that each got.

#1425 [RDCC-6978]Register Org: update column in Organisation table
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalExternalUserFunctionalForV2ApiTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalForV2ApiTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrgWithOtherOrg.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/UpdateOrganisationTest.java
  src/integrationTest/resources/db/migration/V14__alter_organisation.sql
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/OrganisationOtherOrgsCreationRequest.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidator.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationEntityResponseV2.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/domain/Organisation.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
  src/main/resources/db/migration/V14__alter_organisation.sql
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalControllerV2Test.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/OrganisationOtherOrgsCreationRequestTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/domain/OrganisationTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1425

#1442 Change pact broker portal tag
  README.md
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1442, enable_keep_helm

#1440 [RDCC-7020]PRD: Create new table for Bulk Customer Details
  config/owasp/suppressions.xml
  src/main/resources/db/migration/V12__create_bulk_customer_details.sql
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1440, enable_keep_helm

#1446 DTSRD- 1189
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1446

#1445 DTSRD-1173-1
  audit.json
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1445

#1447 DTSRD-1229
  .github/renovate.json
  build.gradle
  renovate.json
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1447
