Repository hmcts/rd-professional-api, pull requests merged in 2023-03, with the labels that each got.

#1359 RDCC-6464: Adding Suppression for `CVE-2023-24998`
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1359

#1357 RDCC-6421 Added renovate.json
  .github/renovate.json
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1357

#1351 Spring boot upgrade 2.7.7
  Dockerfile
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/docs/SwaggerPublisher.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/JwtDecoderMockBuilder.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/KeyGenUtil.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/SpringBootIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/WelcomeController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationMfaStatusController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/DxAddressCreationRequest.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/oidc/JwtGrantedAuthoritiesConverter.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalControllerTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalControllerTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/oidc/JwtGrantedAuthoritiesConverterTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1351

#1361 security audit.json entry
  audit.json
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1361

#1362 RDCC-6505 : Upgrade Libs in PRD API
  build.gradle
  infrastructure/.terraform-version
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, add-or-update, rel:rd-professional-api-pr-1362

#1375 RDCC-6611: suppress CVE-2022-1471
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1375

#1373 fix- CVE fixes in professional Reference Data
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1373

#1378 RDCC-6682: address nightly build failure
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1378
