Repository hmcts/rd-professional-api, pull requests merged in 2023-10, with the labels that each got.

#1448 DTSRD- 1239 . Postgres upgrade to V15
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, add-or-update, rel:rd-professional-api-pr-1448

#1439 Rdcc 7019 : sonar issue fixes for OtherOrgs & PACT test cases
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalExternalControllerV2ProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalExternalControllerV2ProviderTestConfiguration.java
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalInternalControllerV2ProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalInternalControllerV2ProviderTestConfiguration.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtilTest.java
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-professional-api-pr-1439

#1454 DTSRD-1239
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, add-or-update, rel:rd-professional-api-pr-1454

#1463 DTSRD-1456
  build.gradle
  charts/rd-professional-api/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1463

#1468 DTSRD-1466.Remove branches to sync -location demo and master
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1468

#1469 DTSRD-1466.Remove branches to sync -location demo
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1469

#1472 Addresses CVE-2023-42794, CVE-2023-42795 and CVE-2023-45648
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1472

#1470 [RDCC-7088]Civil SDT : Secure the new API with caseworker-civil-admin…
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
  src/functionalTest/resources/application-functional.yaml
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/BulkCustomerDetailsInternalController.java
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-professional-api-pr-1470

#1467 [RDCC-7029]PRD: increase code coverage, mutation coverage for PRD
  src/test/java/uk/gov/hmcts/reform/professionalapi/domain/SingletonOrgTypeTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-professional-api-pr-1467

#1466 [RDCC-7029]PRD: increase code coverage, mutation coverage for PRD
  config/owasp/suppressions.xml
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-professional-api-pr-1466

#1478 suppress CVE-2023-5590
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1478

#1479 DTSRD-1456.suppressing as no known netty handler version available without vulnerability
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1479
