Repository hmcts/rd-professional-api, pull requests merged in 2023-06, with the labels that each got.

#1396 remove suppressions
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1396

#1397 Suppress CVE-2023-20883
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1397

#1398 Update renovate
  renovate.json
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1398

#1395 Update README.md
  README.md
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1395

#1401 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1401

#1400 [RDCC-6780]add sorting in organisation list
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/domain/OrganisationStatus.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1400

#1402 DTSRD-260: NPE when handling ErrorResponse in RefDataUtil
  src/main/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtil.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1402
