Repository hmcts/rd-professional-api, pull requests merged in 2023-04, with the labels that each got.

#1374 RDCC-6548: Addressing Sonar Issues
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/WelcomeController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationMfaStatusController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/DxAddressCreationRequest.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/impl/OrganisationStatusValidatorImpl.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationEntityResponse.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/oidc/JwtGrantedAuthoritiesConverter.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/advice/UnauthorizedExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1374

#1379 Upped spring framework to fix CVE-2023-20860
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1379

#1380 DTSRD 77: update URLs for Preview and AAT
  Jenkinsfile_CNP
  security.sh
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1380

#1381 Fix nightly build with audit.json change
  audit.json
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1381

#1382 Feature/RDCC-6413
  src/integrationTest/resources/db/migration/V11__add_manage_org_roles_enums.sql
  src/main/resources/db/migration/V11__add_manage_org_roles_enums.sql
  src/test/java/uk/gov/hmcts/reform/professionalapi/repository/PrdEnumRepositoryTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1382

#1383 DTSRD-235 - update build.gradle for verifying pact and publish results
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1383

#1386 DTSRD-249: set max heap size for tests
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1386
