Repository hmcts/rd-professional-api, pull requests merged in 2023-11, with the labels that each got.

#1483 DTSRD-1242.adding schema name to connection string
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1483

#1482 Update delete-functional-test-data.sql
  deletescript/sql/delete-functional-test-data.sql
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1482

#1485 Update application.yaml. reverting changes to connection string
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1485

#1487 Update application.yaml
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1487

#1489 DTSRD-1466.Updating schema parameter with hibernate
  config/owasp/suppressions.xml
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1489

#1488 [RDCC-7097]UP : Consumer Pact Test Cases needs to be added
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalInternalControllerProviderTest.java
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1488

#1492 Update acb.tpl.yaml
  acb.tpl.yaml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1492

#1499 Taking the latest change from master
  docker-compose.yml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1499

#1497 fix shchema issue
  src/contractTest/resources/application-contract.yaml
  src/functionalTest/resources/application-functional.yaml
  src/integrationTest/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/professionalapi/dataload/service/AuditServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/domain/OrgAttribute.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/domain/PrdDataSchedularAudit.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/domain/PrdEnum.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/repository/OrgAttributeRepository.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/repository/PrdSchedularAuditRepository.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/repository/ProfessionalUserRepository.java
  src/main/resources/application-camel-routes-common.yaml
  src/main/resources/application-prd-user-details-router.yaml
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-professional-api-pr-1497

#1508 SKU Increase
  infrastructure/prod.tfvars
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, add-or-update, enable_keep_helm, rel:rd-professional-api-pr-1508
