Repository hmcts/rd-professional-api, pull requests merged in 2024-05, with the labels that each got.

#1588 Update schema ownership
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1588, prod/destroy, aat/destroy

#1605 Fix ownership and db access
  infrastructure/main.tf
Labels: ns:rd, prd:rd, prod/destroy, aat/destroy, rel:rd-professional-api-pr-1605

#1606 DTSRD-2750.decommissioning single server
  charts/rd-professional-api/Chart.yaml
  charts/rd-professional-api/values.aat.template.yaml
  charts/rd-professional-api/values.yaml
  infrastructure/main.tf
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, prod/destroy, aat/destroy, rel:rd-professional-api-pr-1606

#1609 Fix db migration issues
  build.gradle
  charts/rd-professional-api/Chart.yaml
  charts/rd-professional-api/values.aat.template.yaml
  gradle/wrapper/gradle-wrapper.properties
  src/contractTest/java/uk/gov/hmcts/reform/professionalapi/BaseProviderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/dataload/camel/AuthorizationDataloadEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/resources/application.yml
  src/integrationTest/resources/db/testmigration/V10__alter_dx_exchange.sql
  src/integrationTest/resources/db/testmigration/V11__add_manage_org_roles_enums.sql
  src/integrationTest/resources/db/testmigration/V12__alter_organisation.sql
  src/integrationTest/resources/db/testmigration/V13__create_org_attribute.sql
  src/integrationTest/resources/db/testmigration/V14__alter_organisation.sql
  src/integrationTest/resources/db/testmigration/V15__scheduler_job_config.sql
  src/integrationTest/resources/db/testmigration/V16__create_bulk_customer_Audit_And_Exception_Tables.sql
  src/integrationTest/resources/db/testmigration/V17__create_bulk_customer_details.sql
  src/integrationTest/resources/db/testmigration/V18__alter_table_bulk_customer_detail.sql
  src/integrationTest/resources/db/testmigration/V19__alter_table_bulk_customer_detail.sql
  src/integrationTest/resources/db/testmigration/V1_1__init_tables.sql
  src/integrationTest/resources/db/testmigration/V20__alter_contact_informatin.sql
  src/integrationTest/resources/db/testmigration/V21__create_user_configured_access_table.sql
  src/integrationTest/resources/db/testmigration/V2__add_enums.sql
  src/integrationTest/resources/db/testmigration/V3__user_identifier_data_type_change.sql
  src/integrationTest/resources/db/testmigration/V4__organisation_identifier_datatype_change.sql
  src/integrationTest/resources/db/testmigration/V5__drop_unique_constraints_add_org_manager.sql
  src/integrationTest/resources/db/testmigration/V6_10__adding_new_user_roles_for_ia_and_fpla.sql
  src/integrationTest/resources/db/testmigration/V6_11__delete_duplicate_jurisdiction_id.sql
  src/integrationTest/resources/db/testmigration/V6_19__adding_new_pba_columns_and_update_existing_pbas.sql
  src/integrationTest/resources/db/testmigration/V6_2__adding_ccd_roles_enum.sql
  src/integrationTest/resources/db/testmigration/V6_3__adding_jurisdiction_enum.sql
  src/integrationTest/resources/db/testmigration/V6_4__updating_jurisdiction_enum.sql
  src/integrationTest/resources/db/testmigration/V6_5__updating_jurisdiction_enum.sql
  src/integrationTest/resources/db/testmigration/V6_6__adding_ccd_roles_enum.sql
  src/integrationTest/resources/db/testmigration/V6_8__adding_super_user_view.sql
  src/integrationTest/resources/db/testmigration/V6__adding_unique_constraints_dropping_status_add_new_field.sql
  src/integrationTest/resources/db/testmigration/V8__adding_uprn_contact_informatin.sql
  src/main/java/uk/gov/hmcts/reform/professionalapi/Application.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalControllerV2.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/feign/UserProfileFeignClient.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/BulkCustomerDetailsInternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalControllerV2.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/domain/Organisation.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidatorTest.java
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-professional-api-pr-1609

#1611 DTSRD-2525: fix flyway migration issue
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1611

#1612 Dtsrd 2766
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1612

#1613 DTSRD-2525: handle flyway out of order
  src/integrationTest/resources/application.yml
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1613
