Repository hmcts/rd-professional-api, pull requests merged in 2024-09, with the labels that each got.

#1676 Update build.gradle - Fixing Nightly build fail
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1676

#1679 Update build.gradle
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1679

#1674 DTSRD-87: address flyway migration issue
  Dockerfile
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1674

#1683 Update build.gradle -revert flyway version
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1683

#1687 Update build.gradle
  Dockerfile
  acb.tpl.yaml
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1687
