Repository hmcts/rd-professional-api, pull requests merged in 2024-10, with the labels that each got.

#1694 DTSRD-3477 Fix local DependencyCheck, version upgraded to 10.0.3
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1694

#1700 Feature/dtsrd 3484
  src/integrationTest/resources/db/testmigration/V22__add_manage_org_roles_enums.sql
  src/main/resources/db/migration/V22__add_manage_org_roles_enums.sql
  src/test/java/uk/gov/hmcts/reform/professionalapi/repository/PrdEnumRepositoryTest.java
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-professional-api-pr-1700

#1703 DTSRD-3583 Mutation Tests BootClassPathSupported False Error - junit5…
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1703

#1702 DTSRD-3580 Jenkins Test Reports to Publish on Failure
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1702

#1704 DTSRD-3623
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1704

#1705 DTSRD-3626 Fix PRD Swagger Page
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1705

#1706 DTSRD-3619
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1706

#1707 DTSRD-3583 PI Test Version Config - pitestVersion added to pitest con…
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-professional-api-pr-1707
