Repository hmcts/rd-professional-api, pull requests merged in 2025-01, with the labels that each got.

#1717 CME-251: Database monitoring and alerting on RD repositories
  Jenkinsfile_CNP
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-professional-api-pr-1717

#1718 CME-294: Update azurerm
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-professional-api-pr-1718

#1728 Update to spring-boot 3.3.7
  build.gradle
Labels: ns:rd, prd:rd

#1734 Fix for build failure
  build.gradle
Labels: ns:rd, prd:rd

#1708 CME-116 update rd-commons-lib
  README.md
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/BulkCivilApiFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/EndpointSecurityTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalExternalUserFunctionalForV2ApiTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalExternalUserFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalForV2ApiTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/CustomSerenityJUnit5Extension.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/CustomSerenityRunner.java
  src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/ToggleEnable.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateMinimalOrganisationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindMFAByUserIDTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindOrganisationsByPbaStatusTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUserByEmailTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/ModifyUserStatusIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveMinimalOrganisationsInfoIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/UpdateOrganisationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/dataload/camel/AuthorizationDataloadEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/docs/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/Application.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/resolver/UserIdArgumentResolver.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/NewUserCreationRequest.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidator.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/impl/OrganisationStatusValidatorImpl.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ProfessionalUsersResponse.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/dataload/processor/FileReadProcessor.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/dataload/processor/HeaderValidationProcessor.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/dataload/route/DataLoadRoute.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/dataload/util/PrdDataExecutor.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/generator/ProfessionalApiGenerator.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/FeatureToggleServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/MfaStatusServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/professionalapi/util/FeatureConditionEvaluation.java
  src/smokeTest/java/uk/gov/hmcts/reform/professionalapi/SmokeTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/dataload/mapper/BulkCustomerDetailsMapperTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/dataload/processor/ExceptionProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/dataload/util/DataLoadUtilTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/helper/OrganisationFixtures.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/FeatureToggleServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/MfaStatusServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/professionalapi/util/FeatureConditionEvaluationTest.java
  web.config
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-professional-api-pr-1708
